/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package votacion;

import java.awt.Color;

/**
 *
 * @author Carlos
 */
public class JFrameCC extends JFrameObserver  {

    /**
     * Creates new form JFrameMAS
     */
    public JFrameCC(Subject sujeto) {
        initComponents();
         this.sujeto=sujeto;
         this.sujeto.agregar(this);
         lblVotosCC.setForeground(Color.red);
         lblCC.setForeground(Color.red);
    }
    @Override
	 public void actualizar(Integer mas,Integer f21,Integer cc) {		
	
             lblVotosMas.setText(mas.toString());
             lblVotos21F.setText(f21.toString());
             lblVotosCC.setText(cc.toString());	
         }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
